### ISSUE TITLE
Module 4 - Adding to CosmosDB at the end doesn't work

### ISSUE THREAD

**Issue by lokijota** [Azure-Samples/serverless-workshop#8]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Do the lab to the end, including the CosmosDB insertion part.

### Any log messages given by the failure
>
Reviews container doesn't exist in CosmosDB and is not created automatically by LogicApps.
Also you're not passing in the partition key in a header + body.

There's also a screenshot specifying ["1", "4"] which is error inducing.

### Expected/desired behavior
>
Insert a record into a CosmosDB container "reviews" including the partition key.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

N/a

### Versions
>

N/a
### Mention any other details that might be useful

I can do a PR if you want.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dbarkol** [comment]
Workshop has been restructured as a series of challenges. An archive branch has been created for reference.
